services:
  - type: web
    name: magicknife-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: "22"
      - key: MONGO_URI
        sync: false
